Add spectator list feature
sdegueldre/pong-3.0 pull request #4
Opened 2020-09-06 10:06 UTC by Shemicalx

These changes add a spectator list to the left of the game-container which shows updates whenever a spectator enters or leaves a room. This way, one can know who and how many other players are watching the game.
![Temp3 112px](https://user-images.githubusercontent.com/28489245/92323449-74b85780-f041-11ea-899d-4b15229da397.png)

2020-09-06 10:13 UTC, ryanwinchester approved these changes
Looks good to me.

2020-09-06 10:26 UTC, sdegueldre requested changes
Changes look good and the feature is nice, unfortunately it looks like you have some form of autoformatter going on, changing a lot of lines for no benefit. It also seems that your changes are based on an older version of the master branch.

Please revert all formatting only changes and rebase your work on top of the latest version of master. Also, can you squash both of your commits? It looks like the second commit fixes a bug introduced by the first.

Thanks for your time and for your work!

2020-09-06 10:26 UTC, sdegueldre commented on README.md
> +
Extra newline

2020-09-06 10:26 UTC, sdegueldre commented on README.md
> +- [Parcel](https://parceljs.org/) for bundling and building
It seems you've used some kind of automatic formatting, while the new formatting is fine, there is nothing wrong with the current one, and this pollutes the commit history. Please revert all changes that are only formatting changes.

2021-02-07 06:52 UTC, closed without merging

2021-02-07 07:06 UTC, sdegueldre commented
Merged at #6. I accidentally pushed master on the PR branch, which automatically closed the PR as merged, removing my ability to push further changes on it.

I have removed all formatting-only changes and split the commit in two (one for the spectator list, and one for the windows compatibility on the --watch flag that wasn't mentioned anywhere)

@Shemicalx thanks for your work!